default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: ecommerce_development

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  database: ecommerce_production
